### ISSUE TITLE
Turn off DEBUG in prod

### ISSUE THREAD

**Issue by flxfxp** [nickpwhite/Beatnik#8]
Your prod website still runs with `DEBUG` to True.

Example: https://www.beatnikapp.com/search?q=https%3A%2F%2Fplay.google.com%2Fmusic%2Fr%2Fm%2FAmyzclwvik4uvqw7ngwk2v36bh4

**Comment by nickpwhite** [comment]
I'm unable to reproduce this issue. Could you provide a screenshot and/or some more information?
